### ISSUE TITLE
Reverting changes doesn't revert the IMDb ID

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#1032]
**Describe the bug**
If you scrape a episode/movie/series and then hit the revert button to undo everything the IMDb ID field doesn't get cleared.

**To Reproduce**
1. Scrape a episode/movie/series
2. Click on revert changes
3. Watch everything except the IMDb ID field revert to its default state.

**Expected behavior**
That the IMDb ID field is reverted to its default empty state.

**MediaElch Version:**
 - [X] 2.6.7-dev (nightly)
 - [ ] 2.6.6 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Comment by bugwelle** [comment]
You don't even have to scrape an episode. Just change the ID by hand, change the episode and change back to it and then try to revert it. Doesn't work (sometimes)...

**Comment by bugwelle** [comment]
Found the issue but I don't understand why it was coded that way in the first place (has been like this for years, before I started):

`reload` (same as revert in this case) for en episode does this: Only re-load episode data if:

 - the NFO was not yet loaded from disk 
 - the episode was not yet reloaded from the (cached) NFO

So when an episode was reloaded once, everything worked. Twice, not anymore.

Will be fixed by #1034
