### ISSUE TITLE
Symlink Mode for File Renamer

### ISSUE THREAD

**Issue by jgkennedy** [Komet/MediaElch#1080]
It would be great if the file renamer could create symlinks instead of moving the actual files. I need to keep the original directory structure for the torrent service. 

Trying to find an open source alternative to FileBot.

**Comment by bugwelle** [comment]
Hi,

interesting idea. But this needs proper specification. I don't have time for this at the moment but PRs are welcome.

What we need to think about:

 - How to differentiate between original files and symlinks? What about users that created symlinks themselves?
 - Should the symlinks exist side by side with the original files?
 - ...

**Comment by ticao2** [comment]
This proposal is interesting.  
I have a question. It's just my curiosity.  
In which folder will the **.nfo** file created by MediaElch be located?  
In the same folder where are the torrent files?  
Or in a new folder created for use by Symlink?

**Comment by rhetr** [comment]
one workaround is to make a hardlink directory manually or with a post-download script. on linux you can do `cp -al <src> <dst>`.

**Comment by bugwelle** [comment]
Hi,

I'm currently going through some of MediaElch's issues and feature requests.

While this feature request is definitely interesting, I don't think that a lot of users would benefit from it (let me know if you think otherwise). And even if implemented, testing all edge cases would be _a lot_ of work, which I simply do not have. Even writing automated tests becomes difficult. Furthermore, symlinks can be tricky. Depending on the filesystem and operating system (e.g. I have no idea how symbolic links work on Windows), the effort to properly test all combinations is too much for me at the moment.

If there are other developers willing to implement and test it, then I'll gladly merge pull requests for it. :-)

I still think your idea is interesting, but I try to avoid new features that I'm personally not using, as too many bugs have flown under my radar because it's not part of my day-to-day workflow.

Kind Regards,
Andre
