### ISSUE TITLE
List of BD movies contains BACKUP and STREAM folders as movies

### ISSUE THREAD

**Issue by vip5912** [Komet/MediaElch#1090]
**Describe the bug**
List of BD movies contains BACKUP and STREAM folders as movies (BACKUP, STREAM, Movie1, Movie2, ...).
Poster and fanart pictures are in BDMV folder.

In version 2.6 (correct behavior):
List of BD movies contains only movie folders (Movie1, Movie2, ...).
Poster and fanart pictures are in movie folder.

File structure:
Movie1
-->BDMV
---->BACKUP
---->STREAM
Movie2
-->BDMV
---->BACKUP
---->STREAM
...

**MediaElch Version:**
 - [ ] 2.8.1-dev (nightly)
 - [x] 2.8.0 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: Ubuntu 20.04)

**Comment by badkarmaboy** [comment]
Can also confirm this behavior on Windows

**Comment by bugwelle** [comment]
Hi,

thank you for pointing out this regression. I think I know what the issue is.

I'm currently at my family's house and don't have access to my own media library. I'll try to reproduce your issue with this script, which creates a basic Blu Ray structure according to Wikipedia  (<https://en.wikipedia.org/wiki/Blu-ray#Directory_and_file_structure>) 

```sh
mkdir MyMovie && cd MyMovie
mkdir BDMV && cd BDMV
mkdir PLAYLIST
mkdir CLIPINF
mkdir -p STREAM/SSIF
mkdir AUXDATA
mkdir BACKUP
touch PLAYLIST/12345.mpls
touch CLIPINF/12345.clpi
touch STREAM/12345.m2ts
touch STREAM/SSIF/12345.ssif
touch AUXDATA/sound.bdmv
touch AUXDATA/12345.otf
touch BACKUP/index.bdmv
touch BACKUP/MovieObject.bdmv
touch BACKUP/12345.mpls
touch BACKUP/12345.clpi
touch index.bdmv
touch MovieObject.bdmv
cd ../..
```

I can confirm this behavior in v2.8.0. Just compiled and checked v2.6.6 and can confirm that the bug does not exist there.

**Comment by bugwelle** [comment]
This commit introduced the bug: https://github.com/Komet/MediaElch/commit/daeb6cae19087ccb1b58e0866d200eb7fa516c8e
