### ISSUE TITLE
Cannot Add movie to new set

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#1129]
I create a new set Wonder Woman Collection
Click on it
Add movie... try to add movie .... no moves are added..
try to add poster and fanart manually to the set.. Cannot..

(latest mediaelch 2.8.0 Windows)

**Comment by bugwelle** [comment]
Thank you very much for reporting this issue!

First issue will be fixed by #1130

What are your settings in "MediaElch" -> "Settings" -> "Movie" -> "Movie Set Poster Filename"?

**Comment by nkatsidis** [comment]
Hello its
folder.jpg

btw why https://dl.bintray.com/komet/MediaElch/ is not updated with latest
night versions?

keep up the great work
Nicolas


Στις Σάβ, 26 Δεκ 2020 στις 9:11 μ.μ., ο/η Andre Meyering <
notifications@github.com> έγραψε:

**Comment by bugwelle** [comment]
> folder.jpg

You could try to use "<setName>.jpg" instead. The file should appear next to your other movie directories. To be honest I don't know how it was supposed to work. I need to look into how Kodi handles it.

> btw why https://dl.bintray.com/komet/MediaElch/ is not updated with latest

Our continuous-integration service has stopped its services for open-source software. All latest nightlies can be found here now: https://bintray.com/bugwelle/MediaElch/MediaElch-Nightly/v2.8.3-dev#files

**Comment by nkatsidis** [comment]
thank you

**Comment by ticao2** [comment]
> 
> ... To be honest I don't know how it was supposed to work. I need to look into how Kodi handles it.

You boldly killed the Kodi v17. But Kodi v19 is coming soon. **:-)**
https://kodi.wiki/view/Releases
And it looks like it will deal with Collection/Set issues quite differently.

Here at MediaElch I remembered these conversations:
https://github.com/Komet/MediaElch/issues/642
https://github.com/Komet/MediaElch/issues/800
https://github.com/Komet/MediaElch/issues/822
https://github.com/Komet/MediaElch/issues/1001
https://github.com/Komet/MediaElch/issues/1129 this conversation.

And in Kodi I found this explanation, which seems to have been modified since the last time I read it.
v18 https://kodi.wiki/view/Movie_sets_artwork
v19 https://kodi.wiki/view/Movie_set_information_folder
v19 https://kodi.wiki/view/Category:Matrix_feature

I think they introduced changes to the Kodi v18.
I don't know if it is worth solving the Collection problems for Kodi v18 or it is better to solve already for Kodi v19.

On the TMDb side, we can actually get confused.
If you use this URL 
https://www.themoviedb.org/movie/10
the URL will be automatically modified to
https://www.themoviedb.org/collection/10-star-wars-collection
That is, the collection IDs belong to the same Movies group. Somewhat confused.

What I understood is that in Kodi there is a **Movies-Sets** folder to store collection folders, which have the collection data.
And there may be a **Movies-Sets Art** folder with folders for each collection to store the artwork.
https://kodi.wiki/view/File:LocalMovieSetsArt01.jpg

So I think MediaElch will need to create these folders as well.
I just didn't understand why they are divided into two folders for each collection.
Maybe in ME it can be a single folder.

Everything is still confused.
I think it would be better for Kodi to address the issue by creating a **.nfo** for the collection.
Regardless of where the folder is. Treat a collection in a similar way to treating a film.

**Comment by bugwelle** [comment]
> You boldly killed the Kodi v17

v17? 😨 

Thanks for your comment. I'll cross-link it from the other issues so that I don't forget this. :-)

**Comment by ticao2** [comment]
> 
> > You boldly killed the Kodi v17
> 
> v17? 😨

## NOT! I was wrong. v16.
My mistake. Excuse me. Now it only reads v16. No more recording.

**Comment by bugwelle** [comment]
> No more recording.

Sorry, what do you mean by "recording"? :-)
Can still read v16 files, though. Do you still use v16 or know someone who does?

**Comment by ticao2** [comment]
> 
> > No more recording.
> 
> Sorry, what do you mean by "recording"? :-)
> Can still read v16 files, though. Do you still use v16 or know someone who does?

record,
register,
write.
Save to v16.
And not. I use, **save**, **save**, the default. v18.
Google Translate sometimes creates problems. **:-)**
I used 2 different words and he translated for the same word, **save**.
And it doesn't always do the same thing.
Worse is when I put **pt-BR** and translation is with **en-US**. Usually.
