### ISSUE TITLE
I'd really like to see Tags in the Custom Movie Scrapper.

### ISSUE THREAD

**Issue by Headspace256** [Komet/MediaElch#1162]
I have to scrape every movie twice, once with imbd to get tags then with Custom scrapper or TMDB to get sets. 

It'd be great if the custom scrapper gave you the option to scrap tags from IMBD as it is already getting other info from IMBD

Thanks for a great application and taking the time to read this.

**Comment by bugwelle** [comment]
Hi,

a rewrite of movie scrapers is planned. This includes the custom movie scraper. ETA: ~next 2 months (hopefully, no promises).

**Comment by Headspace256** [comment]
> Hi,
> 
> a rewrite of movie scrapers is planned. This includes the custom movie scraper. ETA: ~next 2 months (hopefully, no promises).

Thanks that's great, and I promise I won't hold you to it.

**Comment by bugwelle** [comment]
> a rewrite of movie scrapers is planned. This includes the custom movie scraper. ETA: ~next 2 months (hopefully, no promises).

Well, it was more like 2 years. But I finally got to rewrite the movie scrapers. There have been _many_ bugs I found and had to fix before I could rewrite it. 

Now you can select any scraper for tags and it will be used. See https://github.com/Komet/MediaElch/pull/1571
(the change is only so small, because the refactoring of code made it easy)
