### ISSUE TITLE
ADE Scraper does not show Backdrops/Screenshots as Extra Fanarts in UI

### ISSUE THREAD

**Issue by waywit** [Komet/MediaElch#1168]
**Scrapers that don't work:**

 - [ ] IMDb
 - [ ] OFDb
 - [ ] TMDb
 - [ ] TmdbConcert
 - [ ] TheTvDb
 - [ ] TvTunes
 - [ ] AEBN
 - [X] AdultDvDEmpire
 - [ ] HotMovies
 - [ ] VideoBuster

**Details which are wrong / not loaded:**
Scraping movies with ADE scraper originally showed all found "screenshots" in tab "Extra Fanart" and stored it in movie.nfo
Actually the UI is not working properly:
1. If you click on the Fanart on the general Information Tag all Extra Fanart gets loaded
2. The Extra Fanart is also stored in the movie.nfo
But:
The Tab Extra Fanart always stays empty.

**MediaElch Version:**
 - [ ] 2.8.3-dev (nightly)
 - [ ] 2.8.2 stable
 - [X] git master

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [X] Linux (distribution: ___)

**Additional context:**

**Comment by bugwelle** [comment]
Hi,

that's actually the expected behavior (as of now). MediaElch only downloads one backdrop (screenshot). All others are just marked as possible extra fanart which can be downloaded. When you click on an image, the image dialog actually only loads those images that are set as `<thumb>` in `<fanart>` in the NFO.

And the fanart tab only shows those images that were actually downloaded.

What is your expected behavior? :-)

**Comment by waywit** [comment]
Oh, okay... I thought the images were also shown in the backdrops tab before... than this is no issue at all...

**Comment by bugwelle** [comment]
In the (far) future it may be worth adding a button "download extra fanart automatically". But the the moment that's not possible. :)
