### ISSUE TITLE
All agents except IMDB TV, are failing to match when TV folder has (year) in it

### ISSUE THREAD

**Issue by blade316** [Komet/MediaElch#1192]
**Scrapers that don't work:**

 - [*] TVMaze
 - [*] TMDb
 - [*] TheTvDb

**Details which are wrong / not loaded:**
All of my TV show folders have the year in the name e.g. Westworld (2016), 24 (2001), The Blacklist (2013) etc
I have just started using MediaElch and found that almost all my TV shows fail to match when the year is in the search.
All metadata agents except IMDB TV fail to match unless I remove the year from the search text.

e.g. Westworld (2016) won't match, but Westworld will.

I could just use IMDB TV, however it doesn't scrape a lot of the other images and fanart, so this means that if I want MediaElch to go out and automatically scrape all my TV shows AND get the extra fanart and images, I have to use a scraper other than IMDBTV, which means most of the shows will fail to match.

**MediaElch Version:**
 - [*] 2.8.5-dev (nightly)
 - [*] 2.8.4 stable

**Operating System:**
 - [*] Windows
 - [*] macOS
 - [*] Linux (distribution: Docker - UnRAID)

**Additional context:**

Here is some screens

### **IMDB TV matches**

![image](https://user-images.githubusercontent.com/19606551/104857607-71c16200-5965-11eb-9aab-b5d16cc31bf3.png)

### **TBDb TV fails with year**

![image](https://user-images.githubusercontent.com/19606551/104857651-b0571c80-5965-11eb-8a0a-9ad6141ca928.png)

![image](https://user-images.githubusercontent.com/19606551/104857703-062bc480-5966-11eb-9e32-3af6bc57895d.png)

### **TMDb TV matches without year**

![image](https://user-images.githubusercontent.com/19606551/104857688-e98f8c80-5965-11eb-81d7-cbf11790c90c.png)

![image](https://user-images.githubusercontent.com/19606551/104857710-12178680-5966-11eb-8383-60503db0f11d.png)

The TVDb and TVMaze also fail on most TV shows when the year is in the folder name.

I am hoping this could be fixed, so the automated searching works properly on scrapers that also allow the extra artwork at the same time.

**Comment by ticao2** [comment]
Hi @blade316   
I hadn't used the TV Scraper in a long time.
With these new changes I decided to update my Series.
I noticed this behavior different from Scraper for films.
I didn't even consider it very important. But it seems to you it is. **:-)**
I already commented with @bugwelle . I believe it will be resolved.
Watch the conversation at #1176

**Comment by blade316** [comment]
> Hi @blade316
> I hadn't used the TV Scraper in a long time.
> With these new changes I decided to update my Series.
> I noticed this behavior different from Scraper for Movies.
> I didn't even consider it very important. But it seems to you it is. **:-)**
> I already commented with @bugwelle . I believe it will be resolved.
> Watch the conversation at #1176

Thanks so much for the quick reply @ticao2 .... I will keep an eye on that then, fingers crossed! :)

**Comment by ticao2** [comment]
@blade316 , in fact, I believe that clarification is necessary.
In Movies, although we can request with the year in the title, I believe that the search is in fact done without the year.
I realize this because in several cases in the search result we also received titles with another year of release.
But, just for our comfort, we are watching the year of the film we have and so we can more safely choose the data we receive.

**Comment by blade316** [comment]
> @blade316 , in fact, I believe that clarification is necessary.
> In Movies, although we can request with the year in the title, I believe that the search is in fact done without the year.
> I realize this because in several cases in the search result we also received titles with another year of release.
> But, just for our comfort, we are watching the year of the film we have and so we can more safely choose the data we receive.

OK no worries, well let me know if you need any further information from me, or want me to test or clarify anything 👍

**Comment by bugwelle** [comment]
> In Movies, although we can request with the year in the title, I believe that the search is in fact done without the year.

That is partially true. The TMDb scraper checks for a certain pattern and extracts the year if it was provided in the form of `Title (2021)`, `Title 2021` or `Title - (2021)`.
IMDb on the other hand does _not_ extract the year. IMHO MediaElch should simply remove the year from the search query when the dialog opens. Users can add it again for e.g. TMDb. This should also be done for the multi-movie-scraper.

I'll adapt the TV scraper dialog so that the year is removed. Thank you very much for investigating into this. 😄

**Comment by ticao2** [comment]
In the case of TMDb, for Movies, in the UI I see the year of the Movie but in API Request the year is not used.
Is this method that will be implemented for TV Show? That is, TV Show equal to Movie?
I know that IMDB accepts the year for the survey. The others I don't know if they can handle the year.
Now, just to complicate your work a little: **:-)**
I believe that 1 year ago TMDb incorporated the possibility of using the year as a parameter in the API Request.
It's the **&primary_release_year=** parameter.
The API Request would look like this:
`https://api.themoviedb.org/3/search/movie?api_key=THE_KEY&language=pt-BR&query=Ad+Astra&primary_release_year=2019`
I don't know if it is necessary to make this change for TV Show and/or Movies.
For me personally I see no need.
Of course, there are cases where the Movie Title is just a common word.
In fact, there are 2 worse cases, which I know because I suffered from them.
 **M (1931)** - https://www.themoviedb.org/movie/832-m?language=en-US
 **Z (1969)** - https://www.themoviedb.org/movie/2721-z?language=en-US
So, in these cases it is even better to locate the film and use the TMDb ID in the search.
That's what I did at the time.

**Comment by bugwelle** [comment]
> In the case of TMDb, for Movies, in the UI I see the year of the Movie but in API Request the year is not used.
> Is this method that will be implemented for TV Show? That is, TV Show equal to Movie?

TMDb for movies already uses the year as far as I have tested. For TV shows I'm unsure whether we should implement it? How accurate is TMDb for TV shows? I will have to test that first. :)

> I know that IMDB accepts the year for the survey. The others I don't know if they can handle the year.

Good to know. It may be useful for the multi-movie scraper.

> Now, just to complicate your work a little: :-)

😄 👍 

> I believe that 1 year ago TMDb incorporated the possibility of using the year as a parameter in the API Request.
> It's the &primary_release_year= parameter.
> The API Request would look like this:
https://api.themoviedb.org/3/search/movie?api_key=THE_KEY&language=pt-BR&query=Ad+Astra&primary_release_year=2019

We use `year` for movies. I don't really see the difference between the two. Do you know more?  
https://developers.themoviedb.org/3/search/search-movies

> I don't know if it is necessary to make this change for TV Show and/or Movies.
> For me personally I see no need.

Agree. But I'm interested in what `primary_release_year` means. :-)

> Of course, there are cases where the Movie Title is just a common word.
> In fact, there are 2 worse cases, which I know because I suffered from them.
> M (1931) - https://www.themoviedb.org/movie/832-m?language=en-US
total_pages 111 - total_results 2219
> Z (1969) - https://www.themoviedb.org/movie/2721-z?language=en-US
total_pages 90 - total_results 1796
> So, in these cases it is even better to locate the film and use the TMDb ID in the search.
That's what I did at the time.

Oh, that's a very good example! I tested it using `Z` with `year` and `primary_release_year` but the first result is the same... :/

**Comment by ticao2** [comment]
> 
> TMDb for movies already uses the year as far as I have tested. 

I always thought I didn't use it.
Maybe because ME is using only **&year=** and not **&primary_release_year=**.
The difference you can see below in the last item.

> How accurate is TMDb for TV shows? I will have to test that first. :)

I don't have much personal experience with TV Show. My collection is small.
**Year** problems for films exist between **IMDB** and **TMDb**.
This is because the criteria for determining the **Year** are not the same.
**IMDB** uses the first screening, including festivals.
**TMDb** uses the first screening in movie theaters, open to the public.
Therefore, in some cases, the film participated in the Cannes festival in 1969 but had its first public screening in 1970.
Then there will be this difference between IMDB (1969) and TMDb (1970).

But in the case of TV Show there is no such problem. This is because the criteria of the two are the same.
And the big reference is TheTvDB.
I don't know of any difference. But I am not a reliable source. Very small collection.
  
> > Now, just to complicate your work a little: :-)
> 
> 😄 👍
> 
> We use `year` for movies. I don't really see the difference between the two. Do you know more?
> Agree. But I'm interested in what `primary_release_year` means. :-)

The TMDb has 3 date parameters:

- release_date
- primary_release_date
- primary_release_year

For TMDb **Year** is any regional, local **release_date**, premiere date, in any country in the world.
The same film has **released_dates** in as many countries as it was shown.
But **primary_release_date** is the **world premiere** date, the first country to show the film.
The year of this date is the year used as the opening year in the world and shown in brackets on the film page.
 
> Oh, that's a very good example! I tested it using `Z` with `year` and `primary_release_year` but the first result is the same... :/

First result or first page of results?

`M (1931)
https://api.themoviedb.org/3/search/movie?api_key=THE_KEY&language=pt-BR&query=M
Sem o ano = total_pages	111 - total_results	2219
https://api.themoviedb.org/3/search/movie?api_key=THE_KEY&language=pt-BR&query=M&primary_release_year=1931
Com o ano = total_pages	1 - total_results	3

Z (1969)
https://api.themoviedb.org/3/search/movie?api_key=THE_KEY&language=pt-BR&query=Z
Sem o ano = total_pages	90 - total_results	1796
https://api.themoviedb.org/3/search/movie?api_key=THE_KEY&language=pt-BR&query=Z&primary_release_year=1969
Com o ano = total_pages	1 - total_results	8`

The difference is very big. But this case is exceptional.
It can be useful, for example for **Cosmos (1980)** and **Cosmos (2014)**.

Or...
All the King's Men (1949)
All the King's Men (2006)

The Front Page (1931)
The Front Page (1974)

Little Women (1994)
Little Women (2019)

Chocolat (2000)
Chocolat (2016)

Dumbo (1941)
Dumbo (2019)
