### ISSUE TITLE
Mac: Rename window is to large

### ISSUE THREAD

**Issue by mpwg** [Komet/MediaElch#1227]
**Describe the bug**
When I rename files/Folders on the Mac Version, the Rename window is to tall at first launch so the buttons are not visible.
**To Reproduce**

1. Open mediaelch on a Mac (had this on different Mac OS Versions, but I’m using 11.2.1
2. Select a Movie/TV-Show/...
3. Click Rename
4. The Window opens but the Buttons at the bottom are outside the screen (the window is to tall)
5. Close the Window
6. Re-Open the Rename window
7. Its not the correct size.

**Expected behavior**
The Rename Window should have the correct height at first launch
**Screenshots**
The Window
<img width="1440" alt="Bildschirmfoto 2021-02-15 um 14 50 49" src="https://user-images.githubusercontent.com/68284225/107955148-bc062500-6f9d-11eb-8b25-30166b2020d3.png">

**MediaElch Version:**
 - [ ] 2.8.7-dev (nightly)
 - [x] 2.8.6 stable

**Operating System:**
 - [ ] Windows
 - [x] macOS
 - [ ] Linux (distribution: _._)

**Additional context**
MacBook Pro, 15“, Late 2013

**Comment by Megapit** [comment]
Oh! Had this issue for years. And now when i want to create a report someone else is doing it the same day :) 
Made a mini-video about it. Maybe it helps to make clear what happens
[Mediaelch.mkv.zip](https://github.com/Komet/MediaElch/files/5983579/Mediaelch.mkv.zip)

**Comment by bugwelle** [comment]
Hi,

thanks for reporting. I noticed that as well but never got to fix it. 
#1228 will fix this bug (see screenshot there). MediaElch will use a scroll-view.

_Technical Background_: The dialog was so large because when the layout was created, _all_ placeholders were visible. After hiding those that are not relevant (e.g. TV show placeholders for renaming a movie), the layout was adjusted but the size was not. I couldn't figure out why. "sizeHint()" seems to use the _initial_ layout hint, i.e. with all placeholders visible. A scrollview is a fine workaround IMHO.

**Comment by bugwelle** [comment]
A new macOS Nightly can be downloaded from https://bintray.com/bugwelle/MediaElch/MediaElch-Nightly/v2.8.7-dev/view/files#files/

Please ensure to read the CHANGELOG first. :-)
<https://github.com/Komet/MediaElch/blob/master/CHANGELOG.md#287---tbd>

**Comment by Megapit** [comment]
Just want to say: Thank you! Works perfect!
