### ISSUE TITLE
Manually entering a Rating/Votes doesnt save

### ISSUE THREAD

**Issue by snake3ca** [Komet/MediaElch#1283]
If you manually enter a Movie or TV show rating and vote number it doesnt save & leaves a <ratings/> line in the .nfo file.
Ratings work fine if they came from a scaper. 

This is on Mediaelch 2.8.6

**Comment by bugwelle** [comment]
Oh. I haven't tested it with v2.8.6 now, but the good news is that the next MediaElch version supports multiple ratings and I've tested it with manually adding ratings there:

https://github.com/Komet/MediaElch/pull/895#issuecomment-803606189

So this issue should be fixed by the next MediaElch version (and the current nightlies). :-)
