### ISSUE TITLE
Scraping a single episode will pull up show scraper

### ISSUE THREAD

**Issue by vegright** [Komet/MediaElch#1286]
**Describe the bug**
With TV Show is already scraped.  Select a single episode (existing or new) of that show, and scrape.  MediaElch will pull up the show scraper (gives you a selection of shows to pick from), and not the episode scraper.  Note, picking the same show, will scrape the episode properly.  Note if show was previously scraped, but not saved before doing single episode scrape, you will have to scrape show again.

Current work around is to select 2+ episode and scrape.   But for the shows that are new, and only have one episode, this workaround cannot be done.

**To Reproduce**
1. Find existing scraped show and episodes that have either been previously scraped or not scraped
2. Select a single episode that has either been previously scraped or not scraped
3. Scrape (either button, or Ctl-F)
4. See that show dialog appears

**Expected behavior**
I would expect the episode scraper to appear, and retain existing show information.

**MediaElch Version:**
2.8.6 stable

**Operating System:**
Windows
Linux (openSUSE)

**Comment by bugwelle** [comment]
Hi,

sorry, I forgot about this issue.

This is intentional (as of now). You have to select the show's title again. However, you are right in that selecting multiple episode seems to show the correct _tab_. I will fix this for the single-episode scraping. If only one episode is selected, scraping it should not show the "TV show" tab but the episode tab instead. :-)

**Comment by bugwelle** [comment]
Fixed by https://github.com/Komet/MediaElch/commit/93811c8b3b1e35ea50373c5b10c5f3a9609a3bbd
