### ISSUE TITLE
URL based NFO

### ISSUE THREAD

**Issue by forumaks** [Komet/MediaElch#1352]
Is it possible to generate NFO (for movie/tv show/episodes) with url/link for poster, banner, logo, fanart, thumb, diskart etc.?

I meant, all the related photos/backdrops should be inside the nfo only as urls, no download on the pc. Please add this feature if possible.

**Comment by bugwelle** [comment]
Hi,

could you expand a little on your feature request? :)

There are a lot of thumbs with URLs in NFO files. What links are you missing exactly? :)

Regards,
Andre

**Comment by spooki3** [comment]
If I read this post I think it is meant that all poster, banner , logo, fanart should be an URL instead of a locally downloaded file and reference to the file in the NFO.

However if that is the case what is mentioned I would like this to be configurable. Having those URL based would mean internet access is required for those to show up in the mediaplayer of choice. I use mediaelch to populate all the NFOs and download all the required images to have them stored next to the media files before adding adding them to MrMC in my case.
Allowing me to have full control of what is displayed inside MrMC and not having to provide internet access to my mediaplayer. I can keep it completly isolated within my network.

**Comment by ticao2** [comment]
I also use it where I don't have a good internet connection. Radio only. Too bad when it rains or winds.  
So my advancedsettings is set to `<writeThumbUrlsToNfo>false</writeThumbUrlsToNfo>`  
All images are stored in the movie folder.  

And I don't even use Kodi.  
I miss a good UI to be on a 46" TV, 4 meters away.  
If possible with a dark background.  
Maybe someday, some code programmer will make a UI taking advantage of MediaElch directly.
Just dreams, or wishes.  **:-)**

**Comment by bugwelle** [comment]
Hi,

@spooki3 Thank you for clarifying. :-)

To be honest, MediaElch is meant for downloading images to have them locally. That is the use case where I see MediaElch fit into.

While we have a few URLs in our NFOs, I wouldn't got so far as to use them for __all__ images. Furthermore, I'm unsure how far Kodi supports this.

I'll therefore close this feature request, as I also don't have enough time to implement and test this feature. If there are other developers who want to implement this feature, then I'll gladly merge any pull requests. :-)


Regards,
Andre
