### ISSUE TITLE
[FeatureRequest] Support MultiEpisodes-Files

### ISSUE THREAD

**Issue by walterheisenberg** [Komet/MediaElch#147]
I have a few multipart-episodes, which are named like this:
NameoftheSeries.-.S01e03-04-05.avi
This AVI contains the episodes 03, 04 and 05 from Season 01. This is supported in XBMC:
http://wiki.xbmc.org/index.php?title=Video_library/Naming_files/TV_shows#Multi-part_episodes

My dir looks like this:
Captain.Future.uncut_s01e01-02-03_Der\ Herrscher\ von\ Megara.mp4
Captain.Future.uncut_s01e23-24-25_Mitgefangen\ im\ Weltall.mp4
Captain.Future.uncut_s01e04-05-06_Der\ Kampf\ um\ die\ Gravium-Mine.mp4
and so on ...

OT: How can I set this to a "green Feature Request Icon"? ;)

**Comment by MatthewAllan93** [comment]
I have noticed that multi-part episodes work well but when there is a three part episodes, the third part doesn't appear in the episode list to scrape the information. It only shows the two-part episodes.

**Comment by bugwelle** [comment]
Hi there, could you tell me the filenames of the file? MediaElch does not support episode _ranges_. Multi-episode file names should work in the latest nightly, see https://github.com/Komet/MediaElch/issues/1429

If not, could you open another issue, please? That will make sure that your bug is more visible to me. :-)

**Comment by MatthewAllan93** [comment]
Hi, yes the lastest nightly does fix the problem I was having. Thanks, really appreciated :) and the reply about it.
