### ISSUE TITLE
[feature request] convert to series

### ISSUE THREAD

**Issue by tamodolo** [Komet/MediaElch#1536]
A feature to convert movies to series and telling the play position will be awesome.

**Comment by bugwelle** [comment]
Hi,

thanks for this feature request. What do you mean by "telling the play position"?

Since a movie is (most often) a single file, I can't simply convert it to a TV show. Only episodes have video files, i.e. the movie would end up being an episode and I don't know if that's what you want.

Regards,
Andre

**Comment by tamodolo** [comment]
Hi! Thanks for answering me! I didn't add to much info as I didn't want to forget to request this but was also in a hurry at the time. I'll explain now.

This is mostly a feature to solve problems mainly with animes that have movies that continues a season story. The most recent case of that is Demon Slayer (that also had a TV adaptation of the movie). But some series don't bother with that and simply end the thing with a movie or make a second season that continues were the movie left.

Telling Media Elch to use a movie scrapper but also be able to set it as an episode or a single episode season would be great when you think that it's a bit hard to keep track of anime madness of sequences.

When I reseached for a solution to this, KODI actually have a link feature but is not able to set it in a specific position. That's why I'm asking for a solution that allows me to use a movie scrapper to set a movie as an episode.

**Comment by bugwelle** [comment]
Took a few months, but now I finally get to reply:

> But some series don't bother with that and simply end the thing with a movie or make a second season that continues were the movie left.

Yeah. "Venture Bros." did the same. Amazing TV show, which ends with a movie. :smile: 

----

> That's why I'm asking for a solution that allows me to use a movie scrapper to set a movie as an episode.

Thanks for clarifying. The issue is that MediaElch is strictly separated into TV shows and movies (+ other categories). It's not possible to interpret a TV show episode as a movie or similar. Adding such a feature would mean _drastic changes_ to MediaElch, for which I simply don't have the time. It took a ~6 months to answer because there was so much other stuff, that I didn't find the time to look at old issues.

The only workaround I see is to temporarily copy your episode-as-a-movie into a new "movie directory" which you can add in MediaElch's settings. Then reload and scrape the movie. If everything is fine, move the movie to the TV show again (via your system's file explorer). That way, at least Kodi has some way of seeing the NFO file.
