### ISSUE TITLE
Scraping a directory with 40 movies will display just 2 of them (but 40 is recognized)

### ISSUE THREAD

**Issue by opc241** [Komet/MediaElch#1564]
The scraper delivers 2 of 40 movies after reading in the directory. What is the problem here?

**Comment by bugwelle** [comment]
Hi,

could you tell me a bit more about your system? See the issue template here: https://github.com/Komet/MediaElch/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

1. Which operating system do you use?
2. Do you have "separate directories" ("Sep. Verzeichnisse") enabled in your directory settings?

Regards,
Andre

**Comment by opc241** [comment]
Hi Andre, 

no problem, i am using windows and yes, separate directories is enabled.

**Comment by opc241** [comment]
It is a network attached drive i am using. No, the two dispayed movies are not the first one. 

Ok thanks for the hint with the debug, here is the logging file attached, maybe that helps.
[debug.log](https://github.com/Komet/MediaElch/files/11359959/debug.log)

**Comment by bugwelle** [comment]
There are exactly 38 lines with `[MovieXmlReader] No <movie> tag in the document`. My guess: You have either NFO files in each movie directory or other files MediaElch thinks are NFO files. It could be that MediaElch simply ignores movies if we find an NFO file which we can't parse. But of course MediaElch _should_ show the movie, similar to when there isn't any NFO file at all.

To test this idea: Could you go into one of the movie directories that isn't recognized? If there is a `*.nfo` file, e.g. `movie.nfo`, could you paste it's contents here? If you don't want to (after all, they are _your_ movies; I don't need to know which movies you have), could you delete an NFO file if there is any and reload all movies? If it appears, then I have a very good guess what the bug is.

Anyway, thanks for reporting this issue! I will have a look at it tomorrow (or next week).

Thanks,
Andre

**Comment by opc241** [comment]
Hi Andre, 

i could absolutely confirm your idea and tested it by deleting two .nfo files and after that the scraper displays those two movie files. 
I had a look to the .nfo files and there were no <media> tags present (as mentioned by the log file). 
But newertheless, especially in this case i would need MediaElch :)

**Comment by bugwelle** [comment]
Thanks for confirming it. I'll prepare a fix and let you know when a new version is available. :)

**Comment by bugwelle** [comment]
Reproduced locally:

- scan movies
- check movie X exists
- go to movie X's directory
- `touch movie.nfo`
- reload
- confirm movie is "gone" (it is listed, but without any title)

@opc241 I've prepared a fix in https://github.com/Komet/MediaElch/pull/1567 . A new snapshot version is now available at:

- Windows 10 and later: https://mediaelch-downloads.ameyering.de/snapshots/Windows_10_or_later/
- Windows 7 & 8: https://mediaelch-downloads.ameyering.de/snapshots/Windows_7_8/

While I _did_ reproduce that movies were not properly listed, I still saw them in the list, but without a title (only blank lines with icons on the right side). Is it the same for you?

Could you confirm whether it works now? :)

**Comment by opc241** [comment]
Yes i can confirm, that the other 38 movies are listed blank. 

And yes, i could also confirm, that with v. 2.10.1 everything works like a charm. So many thanks for the quick fix to you! I appreciate it!
