### ISSUE TITLE
sorttokens does not work

### ISSUE THREAD

**Issue by AnselmD** [Komet/MediaElch#1613]
**Describe the bug**
Ignore articles when sorting ("The") is checked 
Having those movies - only examples for demonstration:
abc
def
ghi
The abc
The def
The ghi

In MediaElch it is showed like this:
abc
def
ghi
The abc
The def
The ghi

I would expect the following output:
abc
The abc
def
The def
ghi
The ghi

or
abc
abc, The
def
def, The
ghi
ghi, The

**To Reproduce**
see Describe the bug

**Expected behavior**
see Describe the bug

**Screenshots**

**MediaElch Version:**
 - [x] 2.10.2 stable

**Operating System:**
 - [x] Windows

**Additional context**
Should it also influence the rename behavior?

**Comment by bugwelle** [comment]
Thanks for reporting. I was able to reproduce this with the latest `advacedsettings.xml` example. It appears that I had a Copy&Paste error...

I assume you use an advancedsettings.xml file, do you?

__Workaround__:
From your `advancedsettings.xml`, remove the `<exclude>` tag and its contents

It will be fixed in the next MediaElch version.

Regards,
ANdre

**Comment by AnselmD** [comment]
> **Workaround**:
> From your `advancedsettings.xml`, remove the `<exclude>` tag and its contents

Thank you, this works
