### ISSUE TITLE
Duplicate movie Genres, Countries and Studio labels when scrapping

### ISSUE THREAD

**Issue by FrankTheodoloz** [Komet/MediaElch#1635]
**Describe the bug**
Movie Scrapper concatenates/append Genres, Countries and Studio labels instead of replacing them.

**To Reproduce**
Tested on Windows 11. Tested on a fresh Ubuntu 2023.04 as well and all default settings.
1. Select a movie from the list
2. Move on to the Extended tab. Note the Genre, Countries and Studio tags
3. Scrap the infos. Wait for the display to be updated.
4. If the movie details are new, repeat previous step.
5. See that the new details are added to the previous, instead of being replaced.
6. Save the movie details
7. The XML file also contains the duplicated entries.

**Expected behavior**
The scraper should replace the values... or append new labels only.

**Screenshots**
N/A

**MediaElch Version:**
 - [ ] 2.10.5-dev (nightly)
 - [X] 2.10.4 stable

**Operating System:**
 - [X] Windows 11
 - [ ] macOS
 - [X] Linux (distribution: Ubuntu 2023.04)

**Additional context**
When clicking on one of the duplicate tag, it is removed (and the others are well kept), as expected... However the display does not correspond to the reality. Save the movie and see that the removed tag - as well as its duplicates entries - are removed.

Hope this helps, let me know if further details are needed.

**Comment by FrankTheodoloz** [comment]
Reporting the exact same behaviour on Windows 11 with the nightly build (MediaElch_win_Qt6_2.10.5-dev_2023-08-06_17-51_git-master-0e88cd1e).

**MediaElch Version:**
 - [X] 2.10.5-dev (nightly)
 - [X] 2.10.4 stable

**Comment by bugwelle** [comment]
I didn't get to work on this, yet. I'm on vacation for the next two weeks and will work on it after then.

Some notes: I don't want to just clear all requested details. We did that in the past, and already-scraped-details were removed and sometimes not replaced, because no new details were scraped. What I'd prefer is either a setting or a merge strategy. Merging is easy for text fields: it's basically: replace if there is a new value. For genres, it's probably also easy, because genres are often similar in naming (similar between different scrapers). Actors are another topic, because we have to differentiate between actor and role, where different scrapers differ heavily.
