### ISSUE TITLE
NFO file encoding is OEM-US instead of UTF-8

### ISSUE THREAD

**Issue by nextlooper42** [Komet/MediaElch#1647]
**Describe the bug**
NFO file is using OEM-US encoding instead of UTF-8 which supports all language characters. By using OEM-US text cannot be normally loaded in for example in Notepad++ and it shows weird symbols.

**To Reproduce**
Add something with special characters anywhere

**Screenshots**
![Screenshot 2023-09-12 024107](https://github.com/Komet/MediaElch/assets/29764734/defc26a3-d485-4f7c-aa15-699cdae9ca8b)

Text in plot line in screenshot, as it should be:
_Avatar nás zoberie do úžasného sveta Pandory, kde sa jeden muž vydá na veľkolepé dobrodružstvo, kde nakoniec bude musieť bojovať za záchranu ľudí, ktorých miluje a miesto, ktoré sa stane jeho domovom._

**MediaElch Version:**
 - [x] 2.10.5-dev (nightly)
 - [x] 2.10.4 stable

**Operating System:**
 - [x] Windows

**Comment by bugwelle** [comment]
Thanks for reporting. That is... strange. I thought the default of Qt (the framework we use) is UTF-8.

**Comment by bugwelle** [comment]
What we use:

`QXmlStreamWriter`:
> By default, QXmlStreamWriter encodes XML in UTF-8. Different encodings can be enforced using [setCodec](https://doc.qt.io/qt-5/qxmlstreamwriter.html#setCodec)().

@nextlooper42 Do you use the version for Windows 7 to 8 or the version for Windows 10 and later?
I have to test it there. On my Linux machine, everything works as intended:

![Screenshot_20230919_173916](https://github.com/Komet/MediaElch/assets/1667306/2b22e9dd-5e64-416c-aa4e-d4d4248d3520)


```
❯ enca -L none movie.nfo 
Universal transformation format 8 bits; UTF-8
```

Regards,
Andre

**Comment by bugwelle** [comment]
Also, could you upload the incorrect `.nfo` file? That would be helpful (for import/export testing).

**Comment by Klingen29** [comment]
Reproducible for me:
1. MP4 file with German umlauts in the title
2. organize file in folder in Elch
3. rescan directory
4. save file in Elch and thus create NFO file

File content is incorrectly encoded (OEM-US).
However, the movie title is displayed correctly in Elch.

windows 10, testet with Elch 2.10.4 and later
![Zwischenablage-1](https://github.com/Komet/MediaElch/assets/149719280/8c6b15aa-5aa9-441c-aab4-d7e4270c8ddf)
![Zwischenablage-2](https://github.com/Komet/MediaElch/assets/149719280/2b4fe651-e862-449e-bded-4389df614c57)
![Zwischenablage-3](https://github.com/Komet/MediaElch/assets/149719280/c313acfb-6a11-4667-adc1-4a82866f4a4e)

**Comment by bugwelle** [comment]
Thanks! Notepad++ :smile: 

Notepad++ detects the encoding incorrectly. And for whatever reason, I can't change it (even when auto-detection is disabled). However, if you change the language to XML, then you can select "UTF-8" as the encoding without actually changing the file.

Since you're using a German system, I'll provide a guide in German as well. :-)

Als erstes XML als Sprache auswählen. Ich habe das schon gemacht, weshalb das Syntax-Highlighting im Hintergrund schon da ist:

![Screenshot_20231104_193757](https://github.com/Komet/MediaElch/assets/1667306/ccb9b5fa-a456-4b0b-98f3-2ea0fa81f519)

Und dann das Encoding ändern (ändert nichts an der Datei, nur wie Notepad es anzeigt):
![Screenshot_20231104_193815](https://github.com/Komet/MediaElch/assets/1667306/b680cea8-570c-4fc5-bb29-ea6756608693)

Das Encoding zu bestimmen, ist fast unmöglich. Und leider hat auch Notepad da etwas falsch erkannt. Wir speichern alles in UTF-8 ab.

**Comment by Klingen29** [comment]
Danke schön für die nette und ausführliche Antwort!
