### ISSUE TITLE
Broken icons in Linux AppImage

### ISSUE THREAD

**Issue by Seegras** [Komet/MediaElch#1662]
The icons on the left bar in the Linux AppImage version are broken (self-compiled works), so I would assume it can't find them or something like that:
![2023-10-25_11-44](https://github.com/Komet/MediaElch/assets/1655796/02c9e77b-4010-4e7f-8841-62b7baf2a118)

Also, the icons on the top bar are tiny on 4K and badly recognizable (also because of missing contrast).

**Comment by bugwelle** [comment]
Oh! Thanks for reporting it.

The Linux AppImage is built on the oldest system we (theoretically) support. It still uses Qt 5, which can't handle HiDPI screens.

What operating system do you use? :)

Regards,
Andre

**Comment by mihawk90** [comment]
Just as a note: Works perfectly fine for me:

![image](https://github.com/Komet/MediaElch/assets/556162/25e98b70-9779-4790-af28-a46b2b70596d)

This is on Fedora 38 KDE.
Judging by the looks of it this does seem like a DPI issue, because the icons are clearly found, they are just "zoomed in", i.e. too big for the buttons they're supposed to go on. Would also explain why the text is massive in comparison.

My guess is the font-size is scaling with HiDPI (the icons look like font-glyphs to me), while the buttons are not, hence the disparity.

**Comment by bugwelle** [comment]
@mihawk90 Do you use the AppImage on Fedora as well?

By the looks of it, it appears that the SVG's original size is used, instead of being scaled.

**Comment by mihawk90** [comment]
> @mihawk90 Do you use the AppImage on Fedora as well?

Yes (is there something else available?)

Also I just noticed the Concerts and Music icons are a tiny bit cut off on my screenshot as well, but it's obviously nowhere near as much as in the original report.

**Comment by bugwelle** [comment]
The left navigation bar may be fixed by  #1668 (I fixed some scaling issues).

**Comment by bugwelle** [comment]
> Yes (is there something else available?)

I think there is an unofficial MediaElch port for Fedora repositories. Besides that, some users have provided build-instructions for Fedora. :)
https://mediaelch.github.io/mediaelch-doc/contributing/build/fedora_36.html

**Comment by mihawk90** [comment]
> Besides that, some users have provided build-instructions for Fedora. :)

Ah, right. Yeah, too lazy for that when there's something pre-built available :P

**Comment by bugwelle** [comment]
I finally figured out what the issue was: The Qt SVG plugin was not deployed properly.

Should be fixed via https://github.com/Komet/MediaElch/pull/1669

Next Nightly should how proper icons. :)

Thanks for reporting and being patient!
