### ISSUE TITLE
Not fixed: The TvMaze first aired date is still missing. 

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1770]
Issue #1767 is is not fixed not sure why you closed it as completed here are two picture to prove it's not fixed and i just downloaded the latest  snapshot from June 30th.

![2](https://github.com/Komet/MediaElch/assets/161794176/5059ea6a-1270-495c-8805-1bdc48459a11)
![Untitled](https://github.com/Komet/MediaElch/assets/161794176/6788f55d-d18a-4cc1-b50b-ba28e9d241a9)

**Comment by kolbdog323** [comment]
I circled where it shows the first aired date missing.

**Comment by bugwelle** [comment]
@kolbdog323 I closed it, because my tests showed that it works. I just checked again on another system :)

![Screenshot 2024-07-01 at 08 50 19](https://github.com/Komet/MediaElch/assets/1667306/8f4494e2-da38-4b3b-b9ad-11630f498743)

Please ensure that you use the latest version. Could you paste the [developer information](https://mediaelch.github.io/mediaelch-doc/contributing/bug-reports.html#developer-information) here? :)

I've removed older snapshot versions from https://mediaelch-downloads.ameyering.de/snapshots/Windows_10_or_later/

If that version doesn't work, I will have to check on my Windows machine later. (Assuming that you're using Windows)

Regards,
Andre

**Comment by bugwelle** [comment]
@kolbdog323 I just looked at your screenshot: You have __disabled__ the "First Aired" field. That's why MediaElch won't load that! 😄

**Comment by kolbdog323** [comment]
Thanks. My bad didn't realize that.

**Comment by kolbdog323** [comment]
Will close as completed now.
