### ISSUE TITLE
[Scraper] Language selection in dialog

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#442]
*This was originally requested on the old MediaElch forum*

e.g.:
![subler-search-movie](https://user-images.githubusercontent.com/1667306/39472372-2cd2e5a4-4d49-11e8-9123-8ac901198774.jpg)

 - maybe detect default audio stream language

**Comment by stongey** [comment]
I was the original poster of this issue on the k-vibes community forum.

Just a few additional notes:

The screenshot above is from a different piece of software: Subler (https://subler.org/). I use both Subler and MediaElch to help organize my media. I like how Subler allows you to choose the scraping language directly in the scraping dialog. This is much easier than having to go to the preferences to change the scraping language, as in MediaElch.

My media library contains lots of movies and TV Shows in multiple languages, I speak 3 languages and like to have to Media Info presented in the film's native language for those that I understand, and in English otherwise.

The comment on detection of the audio stream language is intended to mean that the scraper dialog could automatically choose the scraping language based on the default or first audio stream language, if specified. If not specified, it would choose the default scraping language set in the preferences.

Or, just allow language selection in the scraping dialog, since that would already save lots of clicks.

**Comment by bugwelle** [comment]
Just a mockup:

![screenshot_20180907_165423](https://user-images.githubusercontent.com/1667306/45226270-afeee700-b2be-11e8-9fba-8fe2e215dd22.png)

**Comment by stongey** [comment]
Looks nice.

**Comment by bugwelle** [comment]
#594 will add this feature. Note: Only TMDb supports more than one language for movies at the moment. :-)

**Comment by bugwelle** [comment]
#802 fixes an issue where the pre-selected language isn't used. There was an error in my implementation. Even though "English" was displayed, another language might have been used for scraping the movie from TMDb. De-selecting and re-selecting it fixes this, though (as a workaround).
