### ISSUE TITLE
[AppImage] Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [Komet/MediaElch#454]
Thanks for providing an AppImage. However, it does not run on the oldest still-supported Ubuntu LTS release, which currently is 14.04:

`AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'CXXABI_1.3.9' not found (required by /run/firejail/appimage/.appimage-7024/AppRun)`

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6 for how to fix this.

Reference:
https://github.com/AppImage/appimage.github.io/pull/569

**Comment by bugwelle** [comment]
So I created #460.

Good news: MediaElch now runs on Ubuntu 14.04. 
Bad news: But not very well (strange behavior like popups that can't be closed)
Good news: I learned a lot about linking and linkers (`ldd`, etc.; still a student :smile: )
Bad news: Still haven't fixed `gstreamer` issues.

Your comment in https://github.com/darealshinji/AppImageKit-checkrt/issues/1 helped a lot.

**Comment by bugwelle** [comment]
I'm sorry, but I really don't know how to fix this. The mentioned behavior ("popups that can't be closed", ...) also happens on Ubuntu 18.04. A lot of other stuff isn't working as expected as well.

In #517 I've created a package script which makes it really easy to build an AppImage. I hope somebody more experienced could have a look at this.

**Comment by bugwelle** [comment]
#594 will (hopefully) fix this. `ffmpeg` is bundled as a static library and `libmediainfo.so.0` is bundled as well because it is loaded at runtime and wasn't detected by linuxdeployqt. :-)

I don't know what took me so long but I think I mixed up some libraries and forgot `.0` at the end of `libmediainfo.so` (the library's name is hard-coded) but no errors were printed.

Well, I'll come back to you after I've tested the upstream version (I successfully tested MediaElch.AppImage using my development branch).
