### ISSUE TITLE
TV Shows filter bug

### ISSUE THREAD

**Issue by alexls74** [Komet/MediaElch#504]
Applying a filter in TV Shows leads to the [crash](https://www.dropbox.com/s/lp8arwjfab0zmdd/MediaElch_2018-07-08-000153_iMac.crash?dl=1).

**Comment by bugwelle** [comment]
Oh. Thanks for reporting.

**Comment by bugwelle** [comment]
This also happens on linux when removing a filter.

**Comment by bugwelle** [comment]
So checked commit 1683ec83b62f3caa62ff073a0a5e18d8e362ef09 (date: 2017-11-26) and it has this error as well. So at least it wasn't a commit by us two. :)

I'll update this comment to keep you up to date. I already tracked down where MediaElch crashes but I can't reproduce this when debugging it (it's as if MediaElch doesn't run into a segfault just because I'm debugging...)

**Comment by alexls74** [comment]
Great Job! Thank you!
