### ISSUE TITLE
[Renamer] Wrong filenames after renaming

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#513]
See https://forum.kodi.tv/showthread.php?tid=136333&pid=2749837#pid2749837

> I used file renamer, for movies its working, but when i use for tv shows, not rename, add +S01E01 and also extension

- [ ] tested
- [ ] reproduced

**Comment by Extarys** [comment]
I think I'm having the same issue.
My current filename: `Vikings S01 E01 Rites Of Passage BluRay.mkv`
Renamed: `S01E01 - Vikings S01 E01 Rites Of Passage BluRay.mkv.mkv
`
Rule: `S<season>E<episode> - <title>.<extension>`

The title is properly fetched and displayed in the main app but it seems `<title>` in renamer take the file name instead of the title of the episode.

Version 2.6.0 AppImage

**Comment by bugwelle** [comment]
Just noticed: `Vikings S01 E01 Rites Of Passage BluRay.mkv` is currently not accepted because of the space between  `S01` and `E01`. This will be fixed soon.

**Comment by bugwelle** [comment]
Hi,

if an episode has not been scraped, MediaElch sets its default name to its filename. That also included the file suffix. This will be fixed by  #954. That PR now removes the file suffix.
