### ISSUE TITLE
Problem with set name

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#554]
Using Latest 2018 08 19 10 57 version in Windows

I have scrapped a movie (which belongs in a set)
now i want to edit name.
i change name and press save 

but the set name becomes duplicated....

lets say i edit SW1 which belongs in SW set.
i make name SW1 New Pope
and press save
now set name becomes like SWSW
if i press again save set name becomes SWSWSW

**Comment by bugwelle** [comment]
Interesting and most likely a bug. Will look into this at the weekend :smiley:

**Comment by bugwelle** [comment]
Can't reproduce this on my mac or linux machine. I will have access to a windows machine next week again and will test it there. :)

**Comment by nkatsidis** [comment]
Set names that have the problem look like this
<set>
        <name>X-Men Collection</name></set>

pressing save again goes like this
<set>
        <name>X-Men Collection</name>X-Men Collection</set>

i have observed that the new nfos look like this
<set>X-Men Collection</set>

maybe is a problem with the old naming scheme ...
is there a way to update all the old naming of sets to the new one?

**Comment by bugwelle** [comment]
Oh, got it. Can reproduce it.

It's because MediaElch stores the set in following format:

```
    <set>Finding Nemo Collection</set>
```

MediaElch does not use `<name>` inside of it and because it does not recognize it, MediaElch appends the new set name.

Thank you very much for reporting this. According to https://kodi.wiki/view/NFO_files/Movies the correct format is

```
<set>
   <name></name>
   <overview></overview>
</set>
```

According to the page's history, this was changed around September 2017 (at least its wiki page was updated around that time). This issue is related to #516

**Comment by bugwelle** [comment]
I'll add a PR that fixes this as soon as possible. I just have to test it a bit more.

Example:
```xml
    <set>
        <name>Harry Potter Collection</name>
        <overview/>
    </set>
```

**Comment by nkatsidis** [comment]
thank you this worked
