### ISSUE TITLE
[Renamer] How-To / Is it implemented?

### ISSUE THREAD

**Issue by Extarys** [Komet/MediaElch#560]
I found this in the docs: [RenamingFiles](https://github.com/Komet/MediaElch/blob/master/doc/RenamingFiles.md). But I cannot find how it works. I cannot find any buttons that would allow me to rename my files.

I'm using version 2.4.3-dev AppImage file.

Is this feature still being implemented or was it removed?

It would be super practical since since last time I used FileBot it became a subscription and my TV Shows are in serious need of love.

Thanks for the help.

**Comment by bugwelle** [comment]
Hello @Extarys,

this is still a feature that MediaElch supports. It seems that we need to update https://mediaelch.github.io/mediaelch-doc/renaming.html so that it will be more obvious as to how the renamer works.

To rename files, you need to select your movies which you want to rename. In the top menu bar you see a yellow icon which is the "rename button". Click it and a window will appear which guides you through renaming files. You can dry run the renamer to see what it does.

I thought FileBot was open source once. Maybe I'm mistaken... 

I'll keep this issue open until I've updated the documentation. 😃

**Comment by Extarys** [comment]
Thanks! The icon looks like a folder. I found it! <3

FYI:

[FileBot](https://github.com/filebot/filebot) github readme:

```
    You may view the source code and learn from it.
    You may build FileBot for private use on unsupported platforms.
    You may NOT use the source code to avoid paying for FileBot or help others to do so.
```

We lost a good app :(

**Comment by bugwelle** [comment]
Thanks :-)

Updated the Renamer: https://mediaelch.github.io/mediaelch-doc/renaming.html
