### ISSUE TITLE
Movie cover browser only display english covers

### ISSUE THREAD

**Issue by pace6666** [Komet/MediaElch#579]
Even if other language is selected in parameters

**Comment by bugwelle** [comment]
Hello,

thanks for reporting this! What scraper are you using to load movie covers and other images?

**Comment by pace6666** [comment]
Tmdb

Le mer. 5 sept. 2018 00 h 57, Andre Meyering <notifications@github.com> a
écrit :

**Comment by bugwelle** [comment]
Okay, can reproduce this. :-)
This happens because cleararts, logos and other images are loaded from fanart.tv. Not all images are loaded from TMDb. Set the language of `fanart.tv` in the settings panel to your preferred language and it should work as expected.

This is indeed confusing. This should definitely be documented or better: it should be shown in the scraper dialog, which image is loaded from which website.

**Comment by pace6666** [comment]
Thanks, it seems to display more covers with your tip. Thank you.  I use
Mediaelch for years and it's way the best solution to manage movies stored
in my hard disk. I really like the interface, filter search option is
awesome! The only missing thing, as my concern, is to export partial
database based on filter search criterias.

Thank you!!!

Le mer. 5 sept. 2018 13 h 55, Andre Meyering <notifications@github.com> a
écrit :

**Comment by bugwelle** [comment]
With "export" you mean the exporter as explained on https://mediaelch.github.io/mediaelch-doc/export/themes.html ? :smiley:

**Comment by pace6666** [comment]
Yes! or a way to export selection to text or CSV

Le mer. 5 sept. 2018 14 h 45, Andre Meyering <notifications@github.com> a
écrit :

**Comment by bugwelle** [comment]
@pace6666 I've added a short note about the fanart.tv confusion to https://mediaelch.github.io/mediaelch-doc/movie/index.html#search-scrape-new-movies

For your CSV feature request I've opened #585
