### ISSUE TITLE
[AEBN] Add genre option

### ISSUE THREAD

**Issue by ludo3163** [Komet/MediaElch#590]
Hello

I test your MediaElch application I saw that there was the scraper aebn but it does not work for Gay movie. Can you add the AEBN GAY? or over

cordially

**Comment by bugwelle** [comment]
![screenshot_20180919_191800](https://user-images.githubusercontent.com/1667306/45774926-95b5f100-bc4e-11e8-8644-f1174e1283ba.png)

In #589 I've added a genre option for AEBN ("genre" because the difference between straight/gay is handled by an URL parameter `genreID`).  
The URL in `AEBN.cpp` is still `https://straight. ...` but whether the content should be straight or gay is actually handled by `genreID` (URl doesn't say anything about the content).
