### ISSUE TITLE
[IMDb] Incorrect director/writer

### ISSUE THREAD

**Issue by tusharbhutt** [Komet/MediaElch#602]
Hello,

MediaElch will not pull the original title when using IMDB as the scraper.  This is for all movies.  When I change to TMDB, the original title is filled correctly.

Regardless of scraper, sometimes the aspect ratio is pulled (e.g.: Hotel Artemis, imdb: `tt5834262`) and other times it is not (e.g Green Room (imdb: `tt4062536`).  Both movies show an aspect ratio of `2.35:1` in IMDB. A suggestion may be that if nothing is scraped, then MediaElch falls back to MediaInfo and uses the stream details.

Also, the IMDB scraper doe snot pull all the actors listed (e.g. Sir Patrick Stewart for Green Room) while TMDB did.

Finally, when IMDB is set to scrape the director and writer, it fills in both fields with the first few actors instead.  When using TMDB, the correct info is used.

This is with the following system info:

MediaElch 2.4.3-dev - Talax (released Sep 21, 2018)

Compiled with Qt version 5.8.0 (32 Release, GCC 5.4.0)
Using Qt version 5.8.0
System: Windows 10 (10.0) (i386-little_endian-ilp32)

I downloaded the files from Sep 24 and the issues persist.

**Comment by bugwelle** [comment]
Hi, 

thanks for the report.

> MediaElch will not pull the original title when using IMDB as the scraper

Indeed. The IMDb  scraper does not support original titles, yet. I've added this feature in #598 
*Note*: Most movies don't have an original title. Only few have it listed, e.g. "Suck Me Shakespeer" which is a German movie. Furthermore this depends on where you're from. I can't force IMDb to load the title in language X because it sends the response based on your IP... That's why I can't add tests for this. 
The mobile site (e.g. [here](https://m.imdb.com/title/tt2987732/?ref_=fn_al_tt_0)) doesn't have this problem but also does not provide all information that we need.

> Regardless of scraper, sometimes the aspect ratio is pulled

The aspect ratio is only pulled from the movie file. No scraper loads that information. Even though IMDb provides it, we rely on the actual movie file.

> Also, the IMDB scraper doe snot pull all the actors listed (e.g. Sir Patrick Stewart for Green Room) while TMDB did.

Actors/Cast is only scraped from the main page, e.g. https://www.imdb.com/title/tt4062536/?ref_=fn_al_tt_1 , and not the "fullcredits" page ( https://www.imdb.com/title/tt4062536/fullcredits?ref_=tt_cl_sm#cast ). Would you like to load "all" actors? This would be another feature request. :)

> Finally, when IMDB is set to scrape the director and writer, it fills in both fields with the first few actors instead. When using TMDB, the correct info is used.
Do you have an example? IMDb should load the writers and directors listed at `Director` and `Writer`, e.g.

```
# From https://www.imdb.com/title/tt4062536/?ref_=fn_al_tt_1
Director: Jeremy Saulnier
Writer: Jeremy Saulnier 
```


Regards,
Andre

**Comment by tusharbhutt** [comment]
Hi,
thanks for the reply.  Yes, the examples of director/writer are for most movies I tried, including those that were listed above by their IMDB number.

As another test, I tried Casablanca (imdb:tt0034583).  The director was Michael Curtiz and the writers were Julius and Phillip Epstein.  TMDB got the correct info, but IMDB pulled the writers as the director as well.  For Carlito's Way (imdb:tt0106519), the Director is Brian De Palma, and writers are Edwin Torres and David Koepp.  The IMDB scraper changes those to 

Director: Brian De Palma, Edwin Torres, David Koepp, Al Pacino, Sean Penn, Penelope Ann Miller
Writer: Edwin Torres, David Koepp, Al Pacino, Sean Penn, Penelope Ann Miller

OK, feature request for full actor list for IDMB then :)

Also... if the info for aspect ratio is pulled from the movie file then that is good, but odd... when I load that file into metabrowser, the aspect ratio field is blank.

Thanks again for a great program, I'll be donating soon.

**Comment by bugwelle** [comment]
> As another test, I tried Casablanca (imdb:tt0034583). The director was Michael Curtiz and the writers were Julius and Phillip Epstein. TMDB got the correct info, but IMDB pulled the writers as the director as well

Thanks! I can reproduce this. Will look into this :)

> OK, feature request for full actor list for IDMB then :)

Created #605

> Also... if the info for aspect ratio is pulled from the movie file then that is good, but odd... when I load that file into metabrowser, the aspect ratio field is blank.

mmhh.. Let me know if you find any other odd behavior. There may be bugs that need to be fixed :)

Regards,
Andre
