### ISSUE TITLE
[Movie] Sort title not set by scraper

### ISSUE THREAD

**Issue by tusharbhutt** [Komet/MediaElch#613]
Hello,

I am unable to load the sort title for any movie being scraped, whether I choose IMDB or TMDB.  This is repeatable on all movies and I do not see it as a separate field under the custom scraper setting so I cannot verify if it's one scraper's settings or the other.

The version is Windows 2.4.3 Dev from October 6

**Comment by ticao2** [comment]
I think TMDb does not have that field. I've never seen.  
Not even in Collections.  
I believe the **Sort Title** field exists to sort the movies in **Collections**.  
I think it should be filled out manually.

**Comment by bugwelle** [comment]
Hi,

thanks for reporting this. The "sort title" is not set by any scraper. It's just for users to fill in if they have movies that need to be sorted in some other way. MediaElch itself does not use this field to sort movies in the movie overview page. It's used for `nfo` files because Kodi uses this field (see [Kodi Wiki](https://kodi.wiki/view/NFO_files/Movies)).

I think we should sort movies by this field. :-)

**Comment by monisriz** [comment]
@bugwelle This can be closed after recent changes.
