### ISSUE TITLE
Custom scraper will not pull title when IMDB is set as source if original title is not in English

### ISSUE THREAD

**Issue by tusharbhutt** [Komet/MediaElch#614]
As per the subject, if IMDB is set as the source for the title when custom scraping, the title fails to load if the original title is in a different language.  Entering the IMDb ID works, and so does using TMDB as the source, but not IMDB just on title.

**Comment by bugwelle** [comment]
Thanks for reporting. I'll try to reproduce this and fix it :)

**Comment by bugwelle** [comment]
Hi there,

it's been a long time since this issue was opened. In the meantime, this issue seems to have been fixed. Steps I took to reproduce:

1. Create movie directory "Oldeuboi" with `movie.mov` video file (English: Oldboy)
1. Reload all movies
1. Set the "title" scraper of the Custom Movie scraper to "IMDb"
1. Search for the movie using the Custom Movie Scraper
1. Click search result
1. Movie loaded

### My Settings
![Screenshot_20200410_153631](https://user-images.githubusercontent.com/1667306/78994772-2c077b80-7b41-11ea-975a-37d861733c0b.png)

### Search Results
![Screenshot_20200410_153528](https://user-images.githubusercontent.com/1667306/78994770-2ad64e80-7b41-11ea-95db-52f17a7164c9.png)

## Loaded Details
![Screenshot_20200410_153611](https://user-images.githubusercontent.com/1667306/78994771-2b6ee500-7b41-11ea-9d13-a799d5d47f37.png)


I tested the same with MediaElch being in another language (German in my case).
