### ISSUE TITLE
Folder rename creates new folder instead of renaming current folder

### ISSUE THREAD

**Issue by BlueBunnyNation** [Komet/MediaElch#625]
![image](https://user-images.githubusercontent.com/24627161/49363513-d7800080-f6af-11e8-81be-2242c1dcb0e4.png)
Instead of changing the movie folder unwanted name, the rename option adds a new folder as a sub-directory of the current unwanted named folder

**Comment by bugwelle** [comment]
This happens if you haven't selected `Sep. folders` in your settings (movie folders). See: https://mediaelch.github.io/mediaelch-doc/settings.html

Solution 1: If your movies are already structured to be separated by folders, make sure that the checkbox `Sep. folders` is checked.  
Solution 2: Don't check `Rename Directories` in the renamer dialog.

Hope this helps :-)
