### ISSUE TITLE
you have to shut down the program in order to load new folder directory

### ISSUE THREAD

**Issue by BlueBunnyNation** [Komet/MediaElch#626]
It would be nice to load the new directory specified in the settings without having to shut down the whole program and reopening it.

**Comment by bugwelle** [comment]
Normally you should only have to click the reload button. Does this not work? :)

**Comment by BlueBunnyNation** [comment]
No it does not work. The reload button only reload the list that was present at the start up of the app. When you remove that list and select another list, and then press the reload button, you will not see the new selected list. Only the initial list when you started the app. Shutting down the app completely and powering back up the app will then show the newly selected list.

**Comment by bugwelle** [comment]
Ok, can't reproduce this, yet.

Could you give me the developer information in the `About` dialog? :-)

**Comment by bugwelle** [comment]
Hi,

I'll close this issue due to inactivity and the fact that I was not able to reproduce it. If your issue still happens in the latest nightlies, let me know and I'll reopen this issue. And also paste the [developer information](https://mediaelch.github.io/mediaelch-doc/contributing/bug-reports.html#developer-information) here. That would be very helpful. :-)
