### ISSUE TITLE
TVDB Scrapper doesn't return results anymore

### ISSUE THREAD

**Issue by slashy** [Komet/MediaElch#630]
Since a few days now I had the tvdb scrapper return results irregular. But as of today I can't seem to get it to find anything. Neither with the id nor the title. I can't update any of my series.

I'm on Windows and I tried the 1.4.2 stable aswell as the latest 1.4.3-dev from today.

**Comment by bugwelle** [comment]
Thanks for reporting. :+1: 
I've tested it on Windows 8.1 with the latest available version. It took three tries to load an episode of "Scrubs". I'll have to test whether it's because of TheTvDb being unreliable (Server Errors) or because of MediaElch. I'm assuming it's the first case because I haven't changed anything TheTvDb specific in the last few weeks. But I'll have to confirm that :-)

**Comment by bugwelle** [comment]
Hi,

does this issue still occur in the latest nightly? We switched to the new TheTvDb API a month ago. That may have fixed your issue.

**Comment by slashy** [comment]
I haven't tested the nightly yet, due to the sorting bug for updated series but I haven't had that problem for a while, which is why I wrote it down as a Server error as you said.

**Comment by bugwelle** [comment]
Thanks. :-)

The sorting (and crashes) have been fixed by #883 (merged yesterday). If something else does not work, please let me know. I consider the latest nightly a release candidate and haven't found and problematic bugs, yet. 😃
