### ISSUE TITLE
Poor presentation of main window using dark theme

### ISSUE THREAD

**Issue by scottfurry** [Komet/MediaElch#640]
Using a dark theme on desktop and I recently made a point of updating Qt environment on Arch Linux derivative so that Qt applications were presented using selected theme.

MediaElch presentation surprised me today. Listing of TV shows on left side is difficult to use (dark blue text on dark background). I'm not sure how this wasn't brought up with bugs #474 or #484 but here it is. Rather difficult to use program this way.

Desktop: XFCE
Theme: Dark Vertex (see https://github.com/horst3180/vertex-theme).
Qt version: 5.12.0
MediaElch ver 2.4.2 - Talax

qt5ct and qt5-styleplugins installed correctly. Variable QT_QPA_PLATFORMTHEME has been set. VLC and other qt5-based applications display normally with theme settings.
![mediaelch_wqt_darktheme](https://user-images.githubusercontent.com/6686571/50662344-3e206480-0f63-11e9-9b07-30e3cb5088f3.png)

**Comment by bugwelle** [comment]
Hi!
Thanks for opening this issue. Version 2.4.2 is not supported anymore. We're in the process of releasing the next version (see #633) and plan on adding official MediaElch repositories (like a PPA for Ubuntu). Where did you get MediaElch from?
 
#407 fixed your issue and version 2.4.3 (nightly versions) works well with a dark theme. But the AppImage of MediaElch still has some problems and may not run on some linux distributions. :-)

For now I'd recommend to either wait for the next version (I'm not sure when this will be the case), download and try the AppImage (see https://mediaelch.github.io/mediaelch-doc/download.html ) or compile MediaElch on your own (see https://mediaelch.github.io/mediaelch-doc/contributing/build.html ).

Btw.  #474 and #484 were just some minor issues that I forgot in #407 :-)
Furthermore there are *many* bugs and other issues in version 2.4.2 that have been fixed in 2.4.3-dev (see [changelog](https://mediaelch.github.io/mediaelch-doc/release-notes.html)).


Regards,
Andre

**Comment by scottfurry** [comment]
Version installed (2.4.2) was done through an Arch package (see here: https://www.archlinux.org/packages/community/x86_64/mediaelch/). Obviously the maintainer had not been made aware the version available was not out of date. Will pass that info along.

**Comment by bugwelle** [comment]
> Can this be arranged?
Yes. A new tag will be added as soon as #633 is approved by @Komet  (MediaElch's author). :smiley:

**Comment by bugwelle** [comment]
FYI, there's now a tag v2.6.0 that points to the latest release :)

**Comment by scottfurry** [comment]
Arch packaging picked up the updated version release when it was made available.
Overall presentation with a dark theme is improved.

**Comment by juup** [comment]
On MediaElch 2.6.0 on Arch there are still white letters on white ground for the name of a selected show or if a episode is selected.
By the way, my theme for the desktop (KDE) has no influence to MediaElch. Even if I choose a dark theme ME looks light.

**Comment by bugwelle** [comment]
#670 fixes some issues. I wasn't able to fix the style issue on the TvShow page, yet.
