### ISSUE TITLE
Ubuntu 18.04: no german umlaut in filter box possible

### ISSUE THREAD

**Issue by waywit** [Komet/MediaElch#663]
Hi

I have found an Issue with german umlauts, which cannot be entered into the filter box in MediaElch 2.6.0 and 2.6.1: "ä", "ö", "ü", "ß" 

I actually use Ubuntu 18.04 with the latest patch level and the umlauts are working correctly everywhere in my system.

Thnaks and best regards.

**Comment by bugwelle** [comment]
Hi,

you mean you can't enter any special characters or just ä, ö, ü, ß? On my system (Kubuntu 18.04) filtering works as expected, i.e. I can enter umlauts and filtering works as well.
How did you install MediaElch?


Regards,
Andre

**Comment by bugwelle** [comment]
Sorry, forgot about this issue due to the number of bug reports :-)  
I'm still not able to reproduce this issue. I'll set up a virtual machine with a fresh Ubuntu installation (and no German translation) and will test it again.

I suspect that the font your system is using may not support German umlauts, could that be? 😃 
What is your system's font family?

**Comment by waywit** [comment]
Hi, no problem, I've also forget about it... ;-) I checked it with my actual build and cannot reproduce it anymore :-) Thanks and best regards!
Jens

**Comment by bugwelle** [comment]
Good to hear, thanks :)
