### ISSUE TITLE
Bug and request

### ISSUE THREAD

**Issue by MaoPlah** [Komet/MediaElch#697]
About MediaElch last AppImage on line release.

1. Open movie folder do not work.
2. Miss a select by ... for movies or folders based on rating and/or date and/or ... other selection query
3. Miss a Copy and a Move and a Delete for selected movies or folder.
4. Miss a language selection on multi-selected scraper.
5. Miss a field in DB for Localized_Title for insert the title in the language of user, and a scraper for Localized_Title in selected language (when you use scraper in a single file name with a selected language you can read appropriate Localized_Title)

I am a user of Media Manager in W (13k movies organized) but I am planning to increase the use of Linux in future.
Have a nice day.
Sorry my language, I am Italian, Thanks
:)

**Comment by bugwelle** [comment]
Hi there,

the AppImage does indeed have quite a few problems. I don't understand point 2 - 5. What do you mean by `Miss a` (probably just a translation issue)?

Thanks for reporting issues with MediaElch. It's very much appreciated. :-)

Regards,
Andre

**Comment by tusharbhutt** [comment]
Perhaps the poster meant the program is "missing" those options? For example, for number two, the program is missing the option to select movies on rating, date, or an arbitrary filter.  I know it can do some like "no IMDB tag" but a truly open filter does not exist like it did in meta<browser/> which sadly seems to be no longer developed.

**Comment by bugwelle** [comment]
> Open movie folder do not work.

Where is the folder stored? On your hard drive, SMB / NFS? 

>  Miss a select by ... for movies or folders based on rating and/or date and/or ... other selection query

If you mean filters then there is another open issue for that. I want to improve the filters in the future but don't have time for that at the moment.

>  Miss a Copy and a Move and a Delete for selected movies or folder.

Move to where? I don't want to implement a "delete" function in MediaElch because if there are bugs for that, MediaElch may accidentally delete a whole directory instead of a file and so on. So I try to avoid that feature altogether. Please use your system's filemanager. :-)

>  Miss a language selection on multi-selected scraper.

Will be added. :-)
Already done so for TV scrapers.

>  Miss a field in DB for Localized_Title for insert the title in the language of user, and a scraper for Localized_Title in selected language (when you use scraper in a single file name with a selected language you can read appropriate Localized_Title)

There is the "original title" for movies. Otherwise I'm not sure what you refer to. :-)

 I'll close this for now. Please reply to this issue if you have further questions and/or want to re-open it.

Regards,
Andre
