### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by jerauf** [Komet/MediaElch#714]
The app is crashing when performing a scan when starting up.

I've got several folders to check but none are marked to scan on startup. However, opening MediaElch, it still scans them and immediately crashes.

How can I fix this?

**Comment by bugwelle** [comment]
Hi there,

what version of MediaElch are you using? :)
And do you use Windows?

There may be a known bug in the latest Nightly on Windows due to a Qt bug.


Regards,
Andre

**Comment by jerauf** [comment]
I'm on a Mac using 2.6.0.

**Comment by bugwelle** [comment]
Thanks. 

Version 2.6.0 (or rather Qt 5.12.1 which is used in that version) has a bug which results in MediaElch crashing.
This issue was reported in https://github.com/Komet/MediaElch/issues/641 and is fixed in v2.6.1-dev 😄 
You can download the latest nightly which should fix this issue.

I didn't have time to release the next version, yet. :)

Regards,
Andre

**Comment by jerauf** [comment]
I don't see how to download. The website sends me here which shows no downloads. https://bintray.com/komet/MediaElch/MediaElch-macOS/2.6.1-dev_2019-05-04_09-33_git-master-eaab0d1

The dropbox link in #641 is dead.

**Comment by alexls74** [comment]
> I don't see how to download.

[2.61-dev](https://bintray.com/komet/MediaElch/download_file?file_path=MediaElch_macOS_2.6.1-dev_2019-05-04_09-33_git-master-eaab0d1.dmg)

[2.60 release (Qt 12.12.3) ](https://www.dropbox.com/s/oyxrkerra4xasv6/MediaElch.zip?dl=1)

**Comment by bugwelle** [comment]
You have to click on "Files" which shows another link to the MediaElch binary :-) 
The links provided by @alexls74 work as well.
