### ISSUE TITLE
libwinpthread-1.dll can not be found at startup

### ISSUE THREAD

**Issue by EdwinDijkshoorn** [Komet/MediaElch#721]
**Describe the bug**

libwinpthread-1.dll cannot be found at startup

**To Reproduce**
1. downloaded build MediaElch_win_2.6.1-dev_2019-05-04_09-29_git-master-eaab0d1.zip
2. MediaElch.exe
3. See error / Crash

**Expected behavior**
MediaElch starts 

**MediaElch Version:**
 - [2.6.1-dev_2019-05-04_09-29

Operating System:**
 - Windows

**Comment by azriel84** [comment]
I also have the same problem... The last version to work normally is 2.6.0 stable...

**Comment by bugwelle** [comment]
Thank you for opening this issue and thank you @azriel84 for confirming it.

I'm not able to reproduce this exact issue, yet. On the other hand MediaElch crashes on Windows due to a bug in Qt. We use `mxe` for Windows nightlies and they only provide Qt 5.12.1 which has some serious bugs with multi-threading (may be related to your pthread issue).

I've opened an issue on https://github.com/mxe/mxe/issues/2346

**Comment by nkatsidis** [comment]
i have installed the libwin file (downloaded from the web, installed it on system32 folder i think) and now the program crashes on startup as i ve reported.

**Comment by azriel84** [comment]
Ανά γειά σου και εγώ το έκανα αυτό και τίποτα τον πουλο Sent from iAzriel S8
-------- Original message --------From: nkatsidis <notifications@github.com> Date: 6/2/19  11:23  (GMT+02:00) To: Komet/MediaElch <MediaElch@noreply.github.com> Cc: azriel84 <azriel84@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [Komet/MediaElch] libwinpthread-1.dll can not be found at startup (#721) i have installed the libwin file (downloaded from the web, installed it on system32 folder i think) and now the program crashes on startup as i ve reported.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Komet/MediaElch/issues/721?email_source=notifications\u0026email_token=AGL3W5E56BFRSSKP75NAADDPYN7RDA5CNFSM4HRFC2X2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWXQRNI#issuecomment-498010293",
"url": "https://github.com/Komet/MediaElch/issues/721?email_source=notifications\u0026email_token=AGL3W5E56BFRSSKP75NAADDPYN7RDA5CNFSM4HRFC2X2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWXQRNI#issuecomment-498010293",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ticao2** [comment]
Win 10 Pro - 64 Bits
MediaElch_2.6.1-2019-06-08_19-46

I only use the Windows Portable version.
I downloaded the **libwinpthread-1.dll** file, and put it in the same folder as the **MediaElch.exe** file, along with the other **.DLLs** of the program.
**Solved** the problem.
I only use for movies. I'm not using it for series.

**Comment by nkatsidis** [comment]
Tried that program crashes...

**Comment by ticao2** [comment]
Portable or Install?
Win, Mac or Linux?
Use TV Show?

**Comment by nkatsidis** [comment]
Latest nightly (its portable)
Windows 64bit..
cant use anything... program crashes .. (cannot start)

**Comment by ticao2** [comment]
Sorry for the question, but ...
You have checked yourself if in the **advancedsettings.xml** file is **portableMode>true</portableMode**?

**Comment by nkatsidis** [comment]
<advancedsettings>
<portableMode>true</portableMode>
</advancedsettings>

used the advancedsettings.xml stored in local directory,

still program crashes

**Comment by ticao2** [comment]
I've never used it, but I know it's possible to create a **DEBUG** file.
You need to make a change to the advanced file:

	<log>
		<debug>false</debug>
		<file></file>
	</log>
Maybe with this information someone can help.

**Comment by nkatsidis** [comment]
I HAVE FOUND THE SOLUTION...... :)
the problem was the wrong libwinpthread-1.dll version....

by donwloading this version and copying it to mediaelch directory
https://osdn.net/projects/sfnet_sixtyfourbitcompiles/downloads/64bit/libwinpthread-1.dll/

mediaelch latest version runs fine :)

**Comment by ticao2** [comment]
Great.
This case is interesting.
The file data, from the link I posted, is different from the file data of your link that you posted.
My Link does not tell if it's 32 or 64 bits. Your Link informs you that it is 64bit.
In my case it worked correctly. And in your case too.

My Link: **56.0 KB (57,379 bytes)**
https://pt.fix4dll.com/libwinpthread1_dll

Your Link: **55,8 KB (57,200 bytes)**
https://osdn.net/projects/sfnet_sixtyfourbitcompiles/downloads/64bit/libwinpthread-1.dll/

**Comment by bugwelle** [comment]
Hi,

sorry for the late answer. `libwinpthread-1.dll` was missing in the packaging process for windows. I've added the missing library in #729
MediaElch may still crash due to #723 

Regards,
Andre

**Comment by azriel84** [comment]
Can confirm, latest nightly works like a charm! Thanks a lot!!!
