### ISSUE TITLE
Crash when adding image via URL

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#832]
**Describe the bug**
When trying to add a image by pasting the URL to it in the Choose Image dialogue the program crash.

**To Reproduce**
1. Click on a series/movie.
2. Click on icon for selecting a poster/fanart/thumb or whatever.
3. Click on Choose Local Image.
4. Paste URL in File Name and click Open.
5. Crash.

**Expected behavior**
The image should end up in the Choose an Image-window.

**MediaElch Version:**
 - [X] 2.6.3-dev (nightly)
 - [ ] 2.6.2 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Comment by bugwelle** [comment]
Hi,

this issue does not occur on macOS and Linux. I was able to reproduce it on Windows, though.
Sadly, it's a Qt issue: https://bugreports.qt.io/browse/QTBUG-71785
Qt is the GUI framework that we use to build MediaElch. Sadly this means there is nothing that I can do at the moment but wait. We rely on [mxe](https://mxe.cc/) to build MediaElch for Windows and mxe has not yet updated their Qt version. I'll ask them if they can. Until they do, this issue can't be fixed.

Regards,
Andre

**Comment by psonnosp** [comment]
OK, nothing major so no worries, thanks :)

**Comment by bugwelle** [comment]
In #958 I finally update Qt to 5.14.2 for Windows. :-)

**Comment by bugwelle** [comment]
Hi,

you can download a version of MediaElch that has fixed this issue here: 

[ ![Download](https://api.bintray.com/packages/bugwelle/MediaElch/MediaElch-win/images/download.svg) ](https://bintray.com/bugwelle/MediaElch/MediaElch-win/_latestVersion)

Due to resource limits, it may take a while until the version is released on https://mediaelch.github.io/mediaelch-doc/download.html
