### ISSUE TITLE
TV shows extrafanart problem

### ISSUE THREAD

**Issue by Araldwenn** [Komet/MediaElch#864]
When trying to add extrafanarts to a new show , it shows nothing, not even searching for pictures, whereas when adding fanart, there are multiple images.

When using an existing show that already has extrafanarts, there's no issue.

**Comment by psonnosp** [comment]
Maybe a dumb question, but have you checked so there actually are any available on the site?

If so it might be related to this https://github.com/Komet/MediaElch/issues/858.

**Comment by bugwelle** [comment]
TheTvDb is seemingly under heavy load. I even have issues searching for TV shows. As I was trying to reproduce your issue, I noticed that all requests ran into a timeout (which is currently set a 3s). 
An issue with MediaElch is that it does not show any errors (e.g. network errors). That's why the screen simply stays blank and no images appear.

Please wait a day or two and try it again. :-)

**Comment by psonnosp** [comment]
Can this also be the reason to this behavior?
https://imgur.com/a/FF2aEgZ
Trying to select a fanart place you in a very long loop like that shown in the video. Sometimes you get a result and sometimes the only thing to do is to close the program by force.
Or is this something else?

**Comment by bugwelle** [comment]
@psonnosp 
😕 Oh my. Thank you very much for that video. That looks definitely like a bug.
You're not pressing escape, are you?

**Comment by psonnosp** [comment]
No, no interaction on my part after clicking the poster.

**Comment by psonnosp** [comment]
I believe this last part should be moved to a new issue since the same thing also happened when I hit F5 to refresh all movies, the status window that pop up behaves the same way as the fanart window does in the video. At the same time it didn't happen when I did what was in the video.
So seems long fetched that it should have something to do with TheTVDB's serverload.

**Comment by Araldwenn** [comment]
All of this is not the bug I'm experiencing. On the video, you can see the animated "Loading" on the downside of the windows. Mine doesn't have this "loading" animation when searching for extrafanart.

The issue is only happening when i scrape a show that doesn't already have extrafanarts.

For these show, if I search for fanart (so basically the same thing as extrafanart, excepted it's the main background), I have multiple choices, so yes, there are extrafanarts.

**Comment by bugwelle** [comment]
> The issue is only happening when i scrape a show that doesn't already have extrafanarts.

Thanks. I only tried to reproduce this on existing shows 🤦‍♂ 
I now know what you mean and can reproduce this.

This happens because MediaElch has no special TvShowExtraFanart-image-provider set. Even though the window says "Default" as the current image provider, non exist. The images that are loaded are the ones that were scraped from TheTvDb (or rather their URLs). That's why you have to first scrape the movie and only then can you download extra fanart. 

This is confusing and I don't really know why it was implemented that way in the first place. ImageProviders are something I haven't touched that much as of now.

Because there is a work-around, this issue doesn't have the highest importance (other bugs come first). Nonetheless this is unexpected and therefore an issue that I have to fix. 😃

**Comment by Araldwenn** [comment]
I can't download extrafanarts at all, even after scaping 1 time first, saving and rescraping again. I don't understand what's your workaround, there's no way I can download extrafanarts for new shows.

**Comment by psonnosp** [comment]
> Because there is a work-around, this issue doesn't have the highest importance (other bugs come first). Nonetheless this is unexpected and therefore an issue that I have to fix. 😃

That workaround only work if you haven't set <writeThumbUrlsToNfo> to false in advancedsettings.xml so the 'Default' mode has somewhere to get the URL from. Or is 'false' the default behavior now after you fixed #849?

The only workaround to this, with no thumb url in nfo, is to either download the images so you can add them with 'Choose Local Image' or paste the URL to it in the title field.

**Comment by bugwelle** [comment]
I'll create a PR soon that gives the users some more details as to why no images appear:
<img width="849" alt="Screen Shot 2020-01-28 at 14 19 45" src="https://user-images.githubusercontent.com/1667306/73267413-4fc15380-41d9-11ea-93b7-29aa40a64812.png">

**Comment by bugwelle** [comment]
**To summarize:**  
"Default" only loads images whose URLs were downloaded while scraping a movie/TV show/etc.  
Neither Fanart.tv nor any other image provider is queried. If you select another provider like Fanart.tv then it is queried for the movie/TV show by using the correct ID (e.g. TheTvDb id or IMDb id).

However, if a Network error occurs, no error is shown to the user at all. There is also no warning if neither default (i.e. previously scraped image URLs) nor any other image provider is available. This has not only confused you but me as well as I was also under the assumption that Fanart.tv would always be queried.

#876 will fix most if not all of the issues mentioned above. Correct error messages will be printed and the text field will be deactivated if it makes sense (like in the image above).

**Comment by bugwelle** [comment]
The next nightly should report errors if there are any. :-)
Please let me know if there are other issues or if this issue isn't fixed for you. Please note that there are already feature requests for more image providers.
