### ISSUE TITLE
Problem scraping TV Shows with special characters in name

### ISSUE THREAD

**Issue by alexpearce92** [Komet/MediaElch#867]
TV Show scraping currently fails when attempting to scrape titles like "Stargate SG-1" but pulls up the correct result ("Stargate SG-1 (2004)") when scraped with "Stargate SG"

v2.6.2
OSX 10.15.2

**Comment by alexpearce92** [comment]
Update: I'm assuming that the scraper feeds the show title directly to the tvdb api or whatever API is being used. I was getting this problem with the TVDB api. Changing the query to use encode the dash as a space resolved my problem, so the request should be: "https://api.thetvdb.com/search/series?name=Stargate%20SG%201" instead of "https://api.thetvdb.com/search/series?name=Stargate%20SG-1"

**Comment by bugwelle** [comment]
Strange API behavior... Their website works well for:

 - https://www.thetvdb.com/search?query=Stargate+SG-1
 - https://www.thetvdb.com/search?query=Stargate%20SG%201

It seems that your issue will be fixed with the next MediaElch version. v2.6.2 still uses an old API of TheTvDb. With 2.6.3-dev I get results both for `Stargate SG-1` and  `Stargate SG 1` :smiley: 

Because of that I'll close this issue. Please note that I currently can't say when the next stable release will come. Maybe at the end of February.
