### ISSUE TITLE
Error querying image provider

### ISSUE THREAD

**Issue by dzogas** [Komet/MediaElch#900]
**Describe the bug**
When I try to load an image for a tv show manually I get an error querying image provider but this does not happen in all tv shows but in most

**To Reproduce**
1. Go to any show
2. Click on logo to get an image
3. See error / Crash

**Expected behavior**
Show the images from fanart or no images found

**MediaElch Version:**
 - [ ] 2.6.5-dev (nightly)
 - [X] 2.6.4 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)
![image](https://user-images.githubusercontent.com/26818516/74860378-32535580-5351-11ea-975c-c633c4b4b5b1.png)

**Comment by dzogas** [comment]
I also tried to get extra fanart and I got this.
![image](https://user-images.githubusercontent.com/26818516/74861215-a5a99700-5352-11ea-9eee-16e773fa2cd2.png)

**Comment by bugwelle** [comment]
Thanks. I'll look into it on the weekend. :)

**Comment by bugwelle** [comment]
Hi,

the first error can be reproduced. It always happens for the TV show "For Life". We try to load the contents from https://webservice.fanart.tv/v3/tv/364318?api_key=[key] but it fails. The TV show page for "For Life" on fanart.tv is https://fanart.tv/series/364318/for-life/ and also contains no images at all. 
I suspect that the show simply hasn't reached their API server, yet. Maybe due to caching but I don't know that. I can only say that there is nothing we can to about that error. 

*But* we should handle "not found" messages better. I'll improve that. :-)

Regarding your second issue: I cannot reproduce that, yet. I can only assume that MediaElch tried to load an empty URL which therefore does not have a protocol. But I'm unsure on that part. Does this happen in a reproducible way?

**Comment by bugwelle** [comment]
#903 prints a more human readable error message for your first issue :-)
