### ISSUE TITLE
Windows 10 / 32 bit: "This app can't run on your PC"

### ISSUE THREAD

**Issue by Nessus85100** [Komet/MediaElch#906]
**Describe the bug**
Versions 2.6.4 &  2.6.2 plu the latest nightly (2.6.5-dev_2020-02-23_13-55_git-master-af8201b) are giving me the same error above. I try also in portable mode with no luck.

 **MediaElch Version:**
 - [x] 2.6.5-dev (nightly)
 - [x] 2.6.4 stable
 - [x] 2.6.2 stable

**Operating System:**
 - [x] Windows 10

**Comment by bugwelle** [comment]
Hi,

Oh.. Well. Do you have a PC with an ARM processor? What kind of pc do sou have? :)

**Comment by Nessus85100** [comment]
Nope... plain Intel Quad processor.

This is the first time that this happens. Until version 2.6.0 i had never this kind of issue

**Comment by bugwelle** [comment]
Hi, 

I've never heard of that issue before... :-/
Could you send me a screenshot of that error? Are there any more details like *why* the app can't be started? :)

Regards,
Andre

**Comment by alexls74** [comment]
Probably Windows 32-bit version.

**Comment by Nessus85100** [comment]
It's a simple win10 OK dialog with no more details on it. And yes, it's a 32bit version.

**Comment by bugwelle** [comment]
Ooohhh.... Should have asked that first. Thank you @alexls74 

@Nessus85100 MediaElch requires a 64-bit system. I don't intend to publish an official 32-bit version because I can't test it as I don't have a 32-bit CPU. A lot of people see 32-bit systems as too old and even some Linux distributions tried to go 64-bit only.

I could create a Windows 32-bit version for you but in case of crashes, support will become more difficult. I can create a 32-bit Windows version of MediaElch if you want one. :-)

By the way, MediaElch builds on top of Qt. Qt doesn't support 32bit on some Linux distributions anymore. Windows is still supported, though. See https://doc.qt.io/qt-5/supported-platforms.html

PS: I hope that all of MediaElch's latest releases are 64 bit or I've misconfigured the deployment process.

**Comment by Nessus85100** [comment]
Oh well... i didn't know that. I've been using MediaElch for years and never had any problems running on my windows 32bit system till now. I haven't updated for months and my latest version 2.6.0. was working fine.

In any case, since i am not planning to update windows any time soon (to much applications re-installs!) it would be nice if you can build a 32bit version, just to me up-to-date.

Cheers
Nessus

**Comment by bugwelle** [comment]
Ok,

takes longer than I anticipated. I'm missing some packages. It's possible that I won't have time to look into it until next week. :-/

**Comment by bugwelle** [comment]
@psonnosp I finally got around to create a 32-bit version of MediaElch. You can download it at https://bintray.com/bugwelle/MediaElch/download_file?file_path=MediaElch_win_2.6.5-dev_2020-03-11_19-52_git-travis-archer96-961d76e.zip (the `travis-archer96`) is the name of my git branch; `archer96` was my previous GitHub username).

Tested on Windows 8.1:

![Unbenannt](https://user-images.githubusercontent.com/1667306/76458767-5697d480-63db-11ea-8120-d7e537c03f17.JPG)

It took a bit longer because I had to test what new dependencies were necessary. Some libraries had different names....
Please let me know whether everything works as expected. If it does then I may consider adding a "legacy" 32-bit Version for future versions as well. :-)

**Comment by Nessus85100** [comment]
I just downloaded and tested. Everything works fine.
Thank you very much for this.

> Please let me know whether everything works as expected. If it does then I may consider adding a "legacy" 32-bit Version for future versions as well. :-)

That will be great, and i think this will benefit many others like me. 

Thanks
Nessus

**Comment by bugwelle** [comment]
Thanks for your feedback :-)

**Comment by Nessus85100** [comment]
There is a minor issue in this. "Original Name", "Writer" & "Director" fields are not saved if you try to modify them. It keeps getting the old info even if i delete the values completely. I try version 2.6.0 and it works fine. I could properly change the values of all those fields and when open this version (2.6.5-dev) all my edited values with version 2.6.0 were showing fine.

So... with version 2.6.5-dev you cannot edit the values of the "Original Name", "Writer" & "Director" fields.

Thanks
Nessus

**Comment by Nessus85100** [comment]
There is a minor issue in this. "Original Name", "Writer" & "Director" fields are not saved if you try to modify them. It keeps getting the old info even if i delete the values completely. I try version 2.6.0 and it works fine. I could properly change the values of all those fields and when open this version (2.6.5-dev) all my edited values with version 2.6.0 were showing fine.

So... with version 2.6.5-dev you cannot edit the values of the "Original Name", "Writer" & "Director" fields.


**EDIT:** I found another one. If you click to the Poster to change the image, i get no images and there is red text in the top left of the window like this one...
![icon-paypalme](https://i.imgur.com/R2xu2T5.jpg)
...but If choose one of the TMDB or Fanart.tv from the menu on the left then the images are showing fine.

Thanks
Nessus
