### ISSUE TITLE
[Movie Search] TMDb: Wrong language choosen in combo box

### ISSUE THREAD

**Issue by psonnosp** [Komet/MediaElch#916]
**Describe the bug**
Actually not sure if this is a bug or design per default.
Either way it needs to be changed and the chosen language under Settings-Scraper-The Movie DB Language should be chosen by default when scraping a movie.

**To Reproduce**
1. Go to Settings-Scraper-The Movie DB Language and set your language of choice.
2. Click on Movies.
3. Select random movie.
4. Ctrl-F
5. Pre selected language is Arabic (U.A.E.) no matter what you selected in step 1.

**Expected behavior**
That the setting under Settings-Scraper-The Movie DB Language is pre selected when you scrape a movie.

**MediaElch Version:**
 - [X] 2.6.5-dev (nightly)
 - [ ] 2.6.4 stable

**Operating System:**
 - [X] Windows
 - [ ] macOS
 - [ ] Linux (distribution: ___)

**Comment by bugwelle** [comment]
Definitely not by design nor intended. It's even stranger. If I select a language in MediaElch's settings for Tmdb and then search for a movie, `Arabic` is selected in the language dropdown but the results are in the language that I selected in the settings dialog.

Thank you for reporting this issue! :-)
