### ISSUE TITLE
Movie Trailer Downoad Breaks after no trailers foiund on previous movie

### ISSUE THREAD

**Issue by sharkbit** [Komet/MediaElch#940]
When downloading movie trailers, the window will not load properly if the last movie did not return any trailer.

**To Reproduce**
1. Pick a movie that is obscure or might not have trailer (IE Krull 1983)
2. Open Download Trailer.. 
3. Nothing Found in Trailer Download window
4. Close Window
5. Pick a Movie that will have trailer
6. Trailer Download window dose not load fully

**Screenshots**
Step 6 ![broke window](https://user-images.githubusercontent.com/979670/77850309-98789700-719f-11ea-96a8-2f2f12d356dc.png)

**MediaElch Version:**
- MediaElch_win_2.6.5-dev_2020-03-08_18-00_git-master-6e27304

**Operating System:**
 - Windows 10 v 1909

**Comment by bugwelle** [comment]
Thank you for opening this issue. It definitely looks like a serious bug.

**Comment by bugwelle** [comment]
First of all: Thank you for reporting this issue! It has existed even before v2.4.2 which surprises me!

There is a workaround: Don't close the trailer dialog using the system's "X" button but the "Close" button at the bottom of the window. MediaElch didn't handle the "X" button correctly.

This will be fixed by #949. Furthermore I had a look at the TV Tunes feature and it had similar issues which made MediaElch crash. So a big thank you for reporting this because otherwise I wouldn't have looked into it. :-)
