### ISSUE TITLE
Movie Frame as Fanart - Movies

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#965]
It would be great if you could add the ability to save a frame of the movie as a fanart. (it is something that is already implemented for Tv Episodes and Posters)

thank you
Nicolas

**Comment by bugwelle** [comment]
Hi, sure. Screenshots for posters were something requested in https://github.com/Komet/MediaElch/issues/934

I only wanted to enable that feature for posters, because someone requested it. But if you would like to use it for fanart as well, I'll add it.

If you want that feature for "extra fanart", let me know. However, that will take more time.

**Comment by nkatsidis** [comment]
Nah no need for extra fanart... :)

**Comment by bugwelle** [comment]
Will be fixed by #971. Still need to test it, though. My system has some OpenGL issues which prevented me from properly testing it.
